server:
  port: 8087
eureka:
  client:
    region: default
    service-url:
      default-zone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5
spring:
  application:
    name: active-service
  

